const EMOJIS = ['📺','🎵','💻','🎮','📰','🏃','☁️','💰','🛍️','📦','🎬','📱','🔒','📧','🗂️','🎙️','🖥️','📡'];

const CAT_COLORS = {
    'Entertainment':    '#16a34a',
    'Music':            '#0d9488',
    'Software':         '#0284c7',
    'Gaming':           '#7c3aed',
    'News & Reading':   '#65a30d',
    'Health & Fitness': '#059669',
    'Cloud Storage':    '#0891b2',
    'Finance':          '#d97706',
    'Shopping':         '#db2777',
    'Other':            '#6b7280',
};

const KNOWN_SENDERS = {
    'netflix.com':        { name: 'Netflix',               emoji: '📺', cost: 15.49, category: 'Entertainment' },
    'spotify.com':        { name: 'Spotify',               emoji: '🎵', cost: 9.99,  category: 'Music' },
    'amazon.com':         { name: 'Amazon Prime',          emoji: '📦', cost: 14.99, category: 'Shopping' },
    'amazon.co':          { name: 'Amazon Prime',          emoji: '📦', cost: 14.99, category: 'Shopping' },
    'apple.com':          { name: 'Apple One / iCloud',    emoji: '🍎', cost: 9.99,  category: 'Cloud Storage' },
    'google.com':         { name: 'Google One',            emoji: '☁️', cost: 2.99,  category: 'Cloud Storage' },
    'hulu.com':           { name: 'Hulu',                  emoji: '📺', cost: 7.99,  category: 'Entertainment' },
    'disneyplus.com':     { name: 'Disney+',               emoji: '🏰', cost: 13.99, category: 'Entertainment' },
    'max.com':            { name: 'Max (HBO)',              emoji: '📺', cost: 15.99, category: 'Entertainment' },
    'hbo.com':            { name: 'Max (HBO)',              emoji: '📺', cost: 15.99, category: 'Entertainment' },
    'peacocktv.com':      { name: 'Peacock',               emoji: '🦚', cost: 5.99,  category: 'Entertainment' },
    'paramountplus.com':  { name: 'Paramount+',            emoji: '📺', cost: 5.99,  category: 'Entertainment' },
    'crunchyroll.com':    { name: 'Crunchyroll',           emoji: '🎌', cost: 7.99,  category: 'Entertainment' },
    'youtube.com':        { name: 'YouTube Premium',       emoji: '▶️', cost: 13.99, category: 'Entertainment' },
    'twitch.tv':          { name: 'Twitch',                emoji: '🎮', cost: 4.99,  category: 'Gaming' },
    'adobe.com':          { name: 'Adobe Creative Cloud',  emoji: '🎨', cost: 54.99, category: 'Software' },
    'microsoft.com':      { name: 'Microsoft 365',         emoji: '💻', cost: 9.99,  category: 'Software' },
    'dropbox.com':        { name: 'Dropbox',               emoji: '☁️', cost: 9.99,  category: 'Cloud Storage' },
    'github.com':         { name: 'GitHub',                emoji: '🐙', cost: 4.00,  category: 'Software' },
    'notion.so':          { name: 'Notion',                emoji: '📝', cost: 8.00,  category: 'Software' },
    'slack.com':          { name: 'Slack',                 emoji: '💬', cost: 7.25,  category: 'Software' },
    'zoom.us':            { name: 'Zoom',                  emoji: '📹', cost: 14.99, category: 'Software' },
    'canva.com':          { name: 'Canva Pro',             emoji: '🎨', cost: 12.99, category: 'Software' },
    'figma.com':          { name: 'Figma',                 emoji: '🎨', cost: 12.00, category: 'Software' },
    'grammarly.com':      { name: 'Grammarly',             emoji: '✍️', cost: 12.00, category: 'Software' },
    'nordvpn.com':        { name: 'NordVPN',               emoji: '🔒', cost: 3.99,  category: 'Software' },
    'expressvpn.com':     { name: 'ExpressVPN',            emoji: '🔒', cost: 8.32,  category: 'Software' },
    '1password.com':      { name: '1Password',             emoji: '🔑', cost: 2.99,  category: 'Software' },
    'lastpass.com':       { name: 'LastPass',              emoji: '🔑', cost: 3.00,  category: 'Software' },
    'audible.com':        { name: 'Audible',               emoji: '🎧', cost: 14.95, category: 'News & Reading' },
    'nytimes.com':        { name: 'New York Times',        emoji: '📰', cost: 17.00, category: 'News & Reading' },
    'wsj.com':            { name: 'Wall Street Journal',   emoji: '📰', cost: 19.99, category: 'News & Reading' },
    'duolingo.com':       { name: 'Duolingo Plus',         emoji: '🦉', cost: 6.99,  category: 'Health & Fitness' },
    'calm.com':           { name: 'Calm',                  emoji: '🧘', cost: 14.99, category: 'Health & Fitness' },
    'headspace.com':      { name: 'Headspace',             emoji: '🧘', cost: 12.99, category: 'Health & Fitness' },
    'chatgpt.com':        { name: 'ChatGPT Plus',          emoji: '🤖', cost: 20.00, category: 'Software' },
    'openai.com':         { name: 'ChatGPT Plus',          emoji: '🤖', cost: 20.00, category: 'Software' },
    'anthropic.com':      { name: 'Claude Pro',            emoji: '🤖', cost: 20.00, category: 'Software' },
    'patreon.com':        { name: 'Patreon',               emoji: '🎨', cost: 5.00,  category: 'Entertainment' },
    'substack.com':       { name: 'Substack',              emoji: '📧', cost: 5.00,  category: 'News & Reading' },
    'discord.com':        { name: 'Discord Nitro',         emoji: '🎮', cost: 9.99,  category: 'Gaming' },
    'ea.com':             { name: 'EA Play',               emoji: '🎮', cost: 4.99,  category: 'Gaming' },
    'xbox.com':           { name: 'Xbox Game Pass',        emoji: '🎮', cost: 14.99, category: 'Gaming' },
    'playstation.com':    { name: 'PlayStation Plus',      emoji: '🎮', cost: 14.99, category: 'Gaming' },
    'nintendo.com':       { name: 'Nintendo Online',       emoji: '🎮', cost: 3.99,  category: 'Gaming' },
    'midjourney.com':     { name: 'Midjourney',            emoji: '🎨', cost: 10.00, category: 'Software' },
    'cursor.sh':          { name: 'Cursor',                emoji: '💻', cost: 20.00, category: 'Software' },
    'linear.app':         { name: 'Linear',                emoji: '📋', cost: 8.00,  category: 'Software' },
};

const BILLING_KEYWORDS = [
    'receipt', 'invoice', 'billing', 'subscription', 'renewal',
    'payment confirmation', 'order confirmation', 'your order',
    'membership', 'plan', 'charge', 'statement'
];
